language: java

jdk:
  - openjdk14

services:
  - postgresql

before_install:
  - psql -c 'create database tracker;' -U postgres

sudo: false

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: never # default: change
    on_failure: never # default: always

env:
  global:
    - CODECOV_TOKEN="5596a101-fe06-4b56-859e-5eb07388196a"